#!/usr/bin/env python3
"""Create a CSV sample from the cleaned parquet dataset."""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

from pyspark.sql import SparkSession


def parse_args() -> argparse.Namespace:
    project_root = Path(__file__).resolve().parents[1]

    parser = argparse.ArgumentParser(
        description="Export a CSV sample from cleaned NYC taxi parquet data."
    )
    parser.add_argument(
        "--input-path",
        type=Path,
        default=project_root / "data" / "processed" / "clean_taxi_trips.parquet",
        help="Input cleaned parquet path.",
    )
    parser.add_argument(
        "--output-path",
        type=Path,
        default=project_root / "data" / "processed" / "sample_taxi_trips.csv",
        help="Output CSV file path.",
    )
    parser.add_argument(
        "--sample-ratio",
        type=float,
        default=0.05,
        help="Sampling ratio in range (0, 1].",
    )
    parser.add_argument(
        "--sample-size",
        type=int,
        default=200000,
        help="Maximum rows in sample after sampling. Use 0 for no limit.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for deterministic sampling.",
    )
    return parser.parse_args()


def find_part_csv(temp_dir: Path) -> Path:
    parts = list(temp_dir.glob("part-*.csv"))
    if not parts:
        raise FileNotFoundError("No part-*.csv file was generated by Spark.")
    return parts[0]


def main() -> int:
    args = parse_args()

    if args.sample_ratio <= 0 or args.sample_ratio > 1:
        print("ERROR: --sample-ratio must be in range (0, 1].")
        return 2

    if not args.input_path.exists():
        print(f"ERROR: input parquet path not found: {args.input_path}")
        print("Run prepare_data.py first.")
        return 1

    spark = SparkSession.builder.appName("nyc_taxi_convert_sample_to_csv").getOrCreate()

    try:
        print(f"Reading cleaned parquet from: {args.input_path}")
        df = spark.read.parquet(str(args.input_path))

        sample_df = df.sample(withReplacement=False, fraction=args.sample_ratio, seed=args.seed)
        if args.sample_size > 0:
            sample_df = sample_df.limit(args.sample_size)

        sample_count = sample_df.count()
        if sample_count == 0:
            print("ERROR: sample has 0 rows. Increase --sample-ratio or remove strict filters.")
            return 1

        print(f"Sample rows: {sample_count}")

        output_path = args.output_path
        output_path.parent.mkdir(parents=True, exist_ok=True)

        temp_dir = output_path.parent / "_tmp_sample_csv"
        if temp_dir.exists():
            shutil.rmtree(temp_dir)

        sample_df.coalesce(1).write.mode("overwrite").option("header", True).csv(str(temp_dir))

        part_csv = find_part_csv(temp_dir)
        if output_path.exists():
            output_path.unlink()

        part_csv.rename(output_path)
        shutil.rmtree(temp_dir, ignore_errors=True)

        print(f"CSV sample saved to: {output_path}")
        return 0

    except Exception as exc:  # pylint: disable=broad-except
        print(f"ERROR while exporting CSV sample: {exc}")
        return 1

    finally:
        spark.stop()


if __name__ == "__main__":
    sys.exit(main())
